<!-- Footer -->
<div id="footer">
	<div class="row-linked">
		<div class="container">
			<div class="col-md-3">
				<p>
					<a href="#home"><?php echo $this->translate('Menu:@Dashboard'); ?></a>
				</p>
				<p>
					<a href="#blog"><?php echo $this->translate('Menu:@Blog'); ?></a>
				</p>
				<p>
					<a href="#contact"><?php echo $this->translate('Menu:@Contact'); ?></a>
				</p>
				<p>
					<a href="#login"><?php echo $this->translate('Menu:@Account login'); ?></a>
				</p>
			</div>
			<div class="col-md-3">
				<p>
					<a href="#faq"><?php echo $this->translate('Menu:@FAQ'); ?></a>
				</p>
				<p>
					<a href="#license"><?php echo $this->translate('Menu:@Licensing'); ?></a>
				</p>
				<p>
					<a href="#terms-of-service"><?php echo $this->translate('Menu:@Terms of service'); ?></a>
				</p>
				<p>
					<a href="#privacy-policy"><?php echo $this->translate('Menu:@Privacy policy'); ?></a>
				</p>
			</div>
			<div class="col-md-3">&nbsp;</div>
			<div class="col-md-3">
				<h4><?php echo $this->translate('Menu:@Follow us'); ?></h4>
				<br> <a class="fa fa-twitter pb-socialicon" href="#twitter" target="_blank"></a>
				<a class="fa fa-facebook pb-socialicon" href="#facebook" target="_blank"></a>
				<a class="fa fa-google-plus pb-socialicon" href="#google-plus" target="_blank"></a>
			</div>
		</div>
	</div>
	
	<div class="row-copyright">
		<div class="container">
			<div class="col-md-12">
				<span class="pull-right"><?php echo $this->translate('Footer:@Copyright'); ?></span>
			</div>
		</div>
	</div>
</div>
<!-- /.Footer -->