<?php
   	$this->headLink()->appendStylesheet($this->baseUrl('/static/css/default.css'));
?>

<!-- Web title -->
<?php echo $this->headTitle() . PHP_EOL; ?>
<!-- Web title -->

<!-- Meta -->
<?php echo $this->headMeta() . PHP_EOL; ?>
<!-- Meta -->

<!-- Link -->
<?php echo $this->headLink() . PHP_EOL; ?>
<!-- Link -->

<!-- Stylesheet -->
<?php echo $this->headStyle() . PHP_EOL; ?>
<!-- Stylesheet -->

<!-- Javascript -->
<?php echo $this->headScript() . PHP_EOL; ?>
<!-- Javascript -->