<!-- Navigation -->
<div id="navigation" class="navbar navbar-default navbar-fixed-top">
	<div class="container">
	
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-fixed-top-items">
				<span class="icon-bar"></span> 
				<span class="icon-bar"></span> 
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="<?php echo $this->translate('NavbarTop:@Homepage'); ?>"><img src="<?php echo $this->baseUrl('/static/images/logo.png'); ?>" border="0"></a>
		</div>
		
		<div id="navbar-fixed-top-items" class="navbar-collapse collapse">
			<ul class="nav navbar-nav navbar-right">
				<li class="active"><a href="<?php echo $this->baseUrl(); ?>"><?php echo $this->translate('NavbarTop:@Homepage'); ?></a></li>
            <?php if ($this->userSession()->isLogged()) : ?>
            	<li class="dropdown">
			        <a class="dropdown-toggle" role="button" data-toggle="dropdown" href="#"><i class="fa fa-user-plus"></i> <?php echo $this->userSession()->user_fullname ? (string) $this->userSession()->user_fullname  : (string) $this->userSession()->user_name ; ?> <span class="caret"></span></a>
			        <ul class="dropdown-menu">
						<li><a href="<?php echo $this->baseUrl('/session/profile'); ?>"><i class="fa fa-info-circle"></i> <?php echo $this->translate('NavbarTop:@My profile'); ?></a></li>
						<li><a href="<?php echo $this->baseUrl('/session/account'); ?>"><i class="fa fa-user"></i> <?php echo $this->translate('NavbarTop:@Account profile'); ?></a></li>
					</ul>
			    </li>
				<li><a href="<?php echo $this->baseUrl('/session/logout'); ?>"><i class="fa fa-sign-out"></i> <?php echo $this->translate('NavbarTop:@Logout'); ?></a></li>
			<?php else : ?>
				<li><a href="<?php echo $this->baseUrl('/session/login'); ?>"><?php echo $this->translate('LoginForm:@Sign in'); ?></a></li>
				<li><a href="<?php echo $this->baseUrl('/session/registration'); ?>"><?php echo $this->translate('LoginForm:@Sign up'); ?></a></li>
			<?php endif; ?>
            </ul>
		</div>
	</div>
</div>
<!-- /.Navigation -->