<div class="text-center">
	<div class="btn-group">
		<!-- Edit -->
		<a href="<?php echo $this->escape($this->baseUrl('admin/department/edit/id/' . $this->department_id)); ?>" class="btn btn-default btn-sm"><i class="fa fa-edit fa-fw"></i> <?php echo $this->translate('ListView:@Edit'); ?></a>
		<!-- Edit -->
		
		<!-- Subject -->
		<a href="<?php echo $this->escape($this->baseUrl('admin/department/manage-subjects/id/' . $this->department_id)); ?>" class="btn btn-default btn-sm"><i class="fa fa-list fa-fw"></i> <?php echo $this->translate('DepartmentListView:@Manage subjects'); ?></a>
		<!-- Subject -->
		
		<!-- Delete -->
		<a href="javascript:void(0);" onclick="LumiaJS.dataTable.get('<?php echo $this->escape($this->dataGrid()->name); ?>').submitAction('<?php echo $this->escape($this->baseUrl('admin/department/delete/id/' . $this->department_id)); ?>');" class="btn btn-danger btn-sm"><i class="fa fa-trash-o fa-fw"></i> <?php echo $this->translate('ListView:@Delete'); ?></a>
		<!-- Delete -->
	</div>
</div>