<div class="row data-grid-filter">

	<div class="col-lg-12">
	
		<div class="well">
		
			<div class="form-group">
				<div class="input-group">
					<?php echo $this->element->getElement('departmentName')->setAttribs(array('class' => 'form-control')); ?>
					<span class="input-group-btn"><?php echo $this->element->getElement('btnFilter')->setAttribs(array('class' => 'btn btn-default btn-primary')); ?></span>
				</div>
			</div>

		</div>
		
	</div>
	
</div>
