<div class="container">

    <h1 class="thumbnail"><?php echo $this->message; ?></h1>

  <?php if (isset($this->exception)): ?>
  
    <h3 class="thumbnail"><?php echo $this->translate('Message'); ?></h3>
	<pre>
       <?php echo $this->exception->getMessage(); ?>
    </pre>

	<h3 class="thumbnail"><?php echo $this->translate('Stack trace'); ?></h3>
	<pre>
        <?php echo $this->exception->getTraceAsString(); ?>
    </pre>

	<h3 class="thumbnail"><?php echo $this->translate('Request Parameters'); ?></h3>
	<pre>
        <?php echo $this->escape(print_r($this->request->getParams(), true)); ?>
    </pre>

  <?php endif; ?>
  
</div>