<div class="navbar-header navbar-left">
	<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
    </button>
	<a class="navbar-brand" href="<?php echo $this->baseUrl('/admin'); ?>">Lumia CMS</a>
</div>

<ul class="nav navbar-nav navbar-right">
	 
 <?php if ($this->userSession()->isLogged()) : ?>
	 <li class="dropdown">
        <a class="dropdown-toggle" role="button" data-toggle="dropdown" href="#"><i class="fa fa-user-plus"></i> <?php echo $this->userSession()->user_fullname ? (string) $this->userSession()->user_fullname  : (string) $this->userSession()->user_name ; ?> <span class="caret"></span></a>
        <ul class="dropdown-menu">
			<?php if ($this->userSession()->isTeacher()) : ?>
			<li><a href="<?php echo $this->baseUrl('/admin/teacher/profile'); ?>"><i class="fa fa-info-circle"></i> <?php echo $this->translate('NavbarTop:@My profile'); ?></a></li>
			<?php elseif ($this->userSession()->isStudent()) : ?>
			<li><a href="<?php echo $this->baseUrl('/admin/student/profile'); ?>"><i class="fa fa-info-circle"></i> <?php echo $this->translate('NavbarTop:@My profile'); ?></a></li>
			<?php endif; ?>
			<li><a href="<?php echo $this->baseUrl('/admin/user/profile'); ?>"><i class="fa fa-user"></i> <?php echo $this->translate('NavbarTop:@Account profile'); ?></a></li>
			<li><a href="<?php echo $this->baseUrl('/admin/user/rearrange-navbar'); ?>"><i class="fa fa-navicon"></i> <?php echo $this->translate('NavbarTop:@Rearrange left navigation bar'); ?></a></li>
		</ul>
    </li>
    <li><a href="<?php echo $this->baseUrl('/admin/session/logout'); ?>"><i class="fa fa-sign-out"></i> <?php echo $this->translate('NavbarTop:@Logout'); ?></a></li>
<?php endif; ?>
	
</ul>	
