<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<?php echo $this->partial('header.phtml'); ?>
	</head>
	<body>
		<!-- Nav -->
		<?php echo $this->partial('navbar.phtml'); ?>
		<!-- /.Nav -->
		
		<!-- Content -->
		<div id="page-wrapper"><?php echo $this->layout()->content; ?></div>
		<!-- /.Content -->
		
		<!-- Footer -->
		<?php echo $this->partial('footer.phtml'); ?>
		<!-- /.Footer -->
	</body>
</html>
