<div class="text-center">
	<div class="btn-group">
		
		<!-- Delete -->
		<a href="javascript:void(0);" onclick="LumiaJS.dataTable.get('<?php echo $this->escape($this->dataGrid()->name); ?>').submitAction('<?php echo $this->escape($this->baseUrl('/admin/department/delete/mode/subject/subject-id/' . $this->department_subject_id)); ?>');" class="btn btn-danger btn-sm"><i class="fa fa-trash-o fa-fw"></i> <?php echo $this->translate('ListView:@Delete'); ?></a>
		<!-- Delete -->
		
	</div>
</div>