<form name="<?php echo $this->element->getName(); ?>" action="<?php echo $this->element->getAction(); ?>" method="<?php echo $this->element->getMethod(); ?>">
	<?php echo $this->element->getElement('media_id'); ?>
	<div class="panel panel-default">
		<div class="panel-heading">
			<div class="pull-left">
				<?php echo $this->element->getElement('media_url')->setAttribs(array('class' => 'form-control')); ?>
			</div>
			<div class="btn-toolbar pull-right">
					<?php echo $this->element->getElement('btnUpload')->setAttribs(array('class' => 'btn btn-lg btn-primary')); ?>
					<?php //echo $this->element->getElement('btnStop')->setAttribs(array('class' => 'btn btn-lg btn-warning')); ?>
					<?php //echo $this->element->getElement('btnCancel')->setAttribs(array('class' => 'btn btn-lg btn-danger')); ?>
			</div>
			<div class="clearfix"></div>
		</div>
		<div class="panel-body">
			<div class="row">
				<div class="col-lg-12">
					<div class="form-group" id="media_url-queueID"></div>
				</div>
			</div>
		</div>
	</div>
	
	
</form>

<script type="text/javascript">
jQuery(document).ready(function() {
	
	LumiaJS.uploadify.overrides = jQuery.extend(LumiaJS.uploadify.overrides, {
		'formData': {
			'requestType': 'ajax',
			'LUMIASID' : '<?php echo Zend_Session::getId(); ?>'
		},
		'itemTemplate' : '<?php echo addslashes(str_replace(array("\r\n", "\n", "\r"), '', $this->partial('form/uploadify/itemTemplate.phtml'))); ?>',
		'queueID': 'media_url-queueID'
	});

	<?php if (isset($this->element->getView()->fileTypeExts)) : ?>
	LumiaJS.uploadify.overrides['fileTypeExts'] = '<?php echo $this->element->getView()->fileTypeExts; ?>';
	<?php endif; ?>

	<?php if (isset($this->element->getView()->fileTypeDesc)) : ?>
	LumiaJS.uploadify.overrides['fileTypeDesc'] = '<?php echo $this->element->getView()->fileTypeDesc; ?>';
	<?php endif; ?>

	<?php if (isset($this->element->getView()->fileSizeLimit)) : ?>
	LumiaJS.uploadify.overrides['fileSizeLimit'] = '<?php echo $this->element->getView()->fileSizeLimit; ?>';
	<?php endif; ?>

	LumiaJS.admin.media.initUploadify('#<?php echo $this->element->getElement('media_url')->getId(); ?>');
});
</script>