<?php if ($messenger = $this->messenger()) : ?>
<script type="text/javascript">
jQuery(document).ready(function($) {
	<?php 
		foreach ($messenger as $ns => $messages) : 
			
			if (empty($messages)) continue;
			
			array_walk($messages, function (&$msg) {
				$msg = htmlentities($msg, ENT_QUOTES, 'UTF-8');
			})
	
	?>
		$.notify({
			// options
			'message': '<?php echo implode('<br />', $messages); ?>'
		},{
			// settings
			'type': '<?php echo $ns; ?>',
			'placement': {'align': 'right'},
			'offset': 2,
			'delay': 1000
		});
	<?php endforeach; ?>
});
</script>
<?php endif; ?>