<div id="${fileID}" class="col-md-2 uploadify-queue-item">
	<div class="thumbnail">
	<div class="progress"><div class="progress-bar progress-bar-success" role="progressbar" aria-valuemin="0" aria-valuemax="100"></div></div>
	<img id="thumb-${fileID}" class="center-block img-responsive " alt="${fileName} (${fileSize})" src="<?php echo $this->baseUrl('/static/jquery-uploadify/no_files.png'); ?>" />
	<div class="action pull-right">
		<div class="cancel"><a class="btn btn-xs btn-default" href="javascript:void(0);"><i class="glyphicon glyphicon-trash"></i></a></div>
	</div>
	<div class="clearfix"></div>
	</div>
</div>
