<form name="<?php echo $this->element->getName(); ?>" action="<?php echo $this->element->getAction(); ?>" method="<?php echo $this->element->getMethod(); ?>">
	<?php echo $this->element->getElement('chapter_id'); ?>
	<?php echo $this->element->getElement('chapter_subject'); ?>
	
	<div class="row">
		
		<div class="col-lg-6">
		
		    <div class="form-group<?php echo ($this->element->getElement('chapter_name')->hasErrors() ? ' has-error' : ''); ?>">
				<label class="control-label"><?php echo $this->element->getElement('chapter_name')->getLabel(); ?></label> 
				<div class="input-group">
					<span class="input-group-addon"><i class="fa fa-caret-right icon-mandatory"></i></span>
					<?php echo $this->element->getElement('chapter_name')->setAttribs(array('class' => 'form-control')); ?>
				</div>
				<?php echo $this->formErrors($this->element->getElement('chapter_name')->getMessages()); ?>
			</div>
			
			<div class="form-group<?php echo ($this->element->getElement('chapter_order')->hasErrors() ? ' has-error' : ''); ?>">	 
				<label class="control-label"><?php echo $this->element->getElement('chapter_order')->getLabel(); ?></label> 
				<div class="input-group">
					<span class="input-group-addon"></span>
					<?php echo $this->element->getElement('chapter_order')->setAttribs(array('class' => 'form-control')); ?>
				</div>
				<?php echo $this->formErrors($this->element->getElement('chapter_order')->getMessages()); ?>
			</div>
			
			<div class="form-group<?php echo ($this->element->getElement('chapter_status')->hasErrors() ? ' has-error' : ''); ?>">	
				<label class="control-label"><?php echo $this->element->getElement('chapter_status')->getLabel(); ?></label>
				<div class="input-group">
					<?php echo $this->element->getElement('chapter_status')->setOptions(array('label_class' => array('class' => 'radio-inline')))->setSeparator('&nbsp;'); ?>
				</div>
				<?php echo $this->formErrors($this->element->getElement('chapter_status')->getMessages()); ?>
			</div>
			
		</div>
			
	</div>

	<div class="btn-toolbar">
		<?php echo $this->element->getElement('btnSave')->setAttribs(array('class' => 'btn btn-lg btn-primary')); ?>
		<?php echo $this->element->getElement('btnReset')->setAttribs(array('class' => 'btn btn-lg btn-danger')); ?>
	</div>
	
</form>