<form name="<?php echo $this->element->getName(); ?>" action="<?php echo $this->element->getAction(); ?>" method="<?php echo $this->element->getMethod(); ?>">
	<?php echo $this->element->getElement('exam_id'); ?>
	
	<div class="row">
		
		<div class="col-lg-6">
			
			<div class="row">
			
				<div class="col-lg-6">
				
					<div class="form-group<?php echo ($this->element->getElement('exam_code')->hasErrors() ? ' has-error' : ''); ?>">	 
						<label class="control-label"><?php echo $this->element->getElement('exam_code')->getLabel(); ?></label> 
						<div class="input-group">
							<span class="input-group-addon"><i class="fa fa-caret-right icon-mandatory"></i></span>
							<?php echo $this->element->getElement('exam_code')->setAttribs(array('class' => 'form-control')); ?>
						</div>
						<?php echo $this->formErrors($this->element->getElement('exam_code')->getMessages()); ?>
					</div>
					
				</div>
				
				<div class="col-lg-6">
				
					<div class="form-group<?php echo ($this->element->getElement('exam_mark')->hasErrors() ? ' has-error' : ''); ?>">	 
						<label class="control-label"><?php echo $this->element->getElement('exam_mark')->getLabel(); ?></label> 
						<div class="input-group">
							<span class="input-group-addon"><i class="fa fa-caret-right icon-mandatory"></i></span>
							<?php echo $this->element->getElement('exam_mark')->setAttribs(array('class' => 'form-control')); ?>
							<span class="add-on"><i class="icon-th"></i></span>
						</div>
						<?php echo $this->formErrors($this->element->getElement('exam_mark')->getMessages()); ?>
					</div>
					
				</div>
				
			</div>
			
			<div class="form-group<?php echo ($this->element->getElement('exam_status')->hasErrors() ? ' has-error' : ''); ?>">	
				<label class="control-label"><?php echo $this->element->getElement('exam_status')->getLabel(); ?></label>
				<div class="input-group">
					<?php echo $this->element->getElement('exam_status')->setOptions(array('label_class' => array('class' => 'radio-inline')))->setSeparator('&nbsp;'); ?>
				</div>
				<?php echo $this->formErrors($this->element->getElement('exam_status')->getMessages()); ?>
			</div>
			
		</div>
		
		<div class="col-lg-6">
			
			<div class="row">
			
				<div class="col-lg-8">
					<div class="form-group<?php echo ($this->element->getElement('exam_management_start_time')->hasErrors() ? ' has-error' : ''); ?>">
						<label class="control-label"><?php echo $this->element->getElement('exam_management_start_time')->getLabel(); ?></label>
						<div class="input-group date form-datetime">
							<span class="input-group-addon"><i class="fa fa-caret-right icon-mandatory"></i></span>
							<?php echo $this->element->getElement('exam_management_start_time')->setAttrib('class', 'form-control'); ?>
							<div class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></div>
							<div class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></div>
						</div>
						<?php echo $this->formErrors($this->element->getElement('exam_management_start_time')->getMessages()); ?>
					</div>
				</div>
				
				<div class="col-lg-4">
					<div class="form-group<?php echo ($this->element->getElement('exam_management_execution_duration')->hasErrors() ? ' has-error' : ''); ?>">
						<label class="control-label"><?php echo $this->element->getElement('exam_management_execution_duration')->getLabel(); ?></label>
						<div class="input-group">
							<span class="input-group-addon"><i class="fa fa-caret-right icon-mandatory"></i></span>
							<?php echo $this->element->getElement('exam_management_execution_duration')->setAttrib('class', 'form-control'); ?>
							<span class="input-group-addon suffix"><?php echo $this->translate('ExamForm:@Minute'); ?></span>
						</div>
						<?php echo $this->formErrors($this->element->getElement('exam_management_execution_duration')->getMessages()); ?>
					</div>
				</div>
				
			</div>
			
			<div class="form-group<?php echo ($this->element->getElement('exam_subject')->hasErrors() ? ' has-error' : ''); ?>">	
				<label class="control-label"><?php echo $this->element->getElement('exam_subject')->getLabel(); ?></label>
				<div class="input-group">
					<span class="input-group-addon"><i class="fa fa-caret-right icon-mandatory"></i></span>
					<?php echo $this->element->getElement('exam_subject')->setAttribs(array('class' => 'form-control')); ?>
				</div>
				<?php echo $this->formErrors($this->element->getElement('exam_subject')->getMessages()); ?>
			</div>
				
		</div>
		
		<?php if ($this->element->getSubForm('dependencyStudents')->isErrors()) : ?>
		<div class="col-lg-12">
			<div class="alert alert-danger" role="alert">
			<?php foreach ($this->element->getSubForm('dependencyStudents')->getErrorMessages() as $errorMessage) : ?>
				<div>
					<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
					<span class="sr-only">Error:</span>
					<?php echo $errorMessage; ?>
				</div>
		    <?php endforeach; ?>
			</div>
		</div>
		<?php endif; ?>
		
		<div class="col-lg-12" id="exam-classes">
			<?php echo $this->render('form/list-classes.phtml'); ?>
			<?php echo $this->render('form/list-students.phtml'); ?>
		</div>
		
		<?php if ($this->element->getSubForm('dependencyQuestions')->isErrors()) : ?>
		<div class="col-lg-12">
			<div class="alert alert-danger" role="alert">
			<?php foreach ($this->element->getSubForm('dependencyQuestions')->getErrorMessages() as $errorMessage) : ?>
				<div>
					<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
					<span class="sr-only">Error:</span>
					<?php echo $errorMessage; ?>
				</div>
		    <?php endforeach; ?>
			</div>
		</div>
		<?php endif; ?>
		
		<div class="col-lg-12" id="exam-questions">
			<?php echo $this->render('form/list-questions.phtml'); ?>
		</div>
		
	</div>

	<div class="btn-toolbar">
		<?php echo $this->element->getElement('btnSave')->setAttribs(array('class' => 'btn btn-lg btn-primary')); ?>
		<?php echo $this->element->getElement('btnReset')->setAttribs(array('class' => 'btn btn-lg btn-danger')); ?>
	</div>
	
</form>