<div class="text-center">
	<div class="btn-group">
		<!-- Edit -->
		<a href="<?php echo $this->escape($this->baseUrl('admin/chapter/edit/subject/' . $this->subject_id . '/id/' . $this->chapter_id)); ?>" class="btn btn-default btn-sm"><i class="fa fa-edit fa-fw"></i> <?php echo $this->translate('ListView:@Edit'); ?></a>
		<!-- Edit -->
		
		<!-- Delete -->
		<a href="javascript:void(0);" onclick="LumiaJS.dataTable.get('<?php echo $this->escape($this->dataGrid()->name); ?>').submitAction('<?php echo $this->escape($this->baseUrl('admin/chapter/delete/subject/' . $this->subject_id . '/id/' . $this->chapter_id)); ?>');" class="btn btn-danger btn-sm"><i class="fa fa-trash-o fa-fw"></i> <?php echo $this->translate('ListView:@Delete'); ?></a>
		<!-- Delete -->
	</div>
</div>