<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><?php echo $this->translate('PageHeader:@Manage subjects');?></h1>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading"><?php echo $this->translate('Form:@Edit');?></div>
            <div class="panel-body"><?php echo $this->form; ?></div>
        </div>
    </div>
</div>